name: oci-spec-ci
on:
  # Triggers the workflow on push or pull request events but only for the v1.1beta_helm_pkg_update_lber_ay branch
  push:
    branches: [ v1_oci_spec ]
  pull_request:
    branches: [ v1_oci_spec ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_AGENT_TAG: "enterpriseconnect/agent:v1"
      DOCKER_HUB_PLUGIN_TAG: "enterpriseconnect/plugins:v1"
      DOCKER_HUB_LOADBALANCER_TAG: "enterpriseconnect/lb:v1"
    #- DOCKER_HUB_BUILD_TAG="enterpriseconnect/build:v1"
      GITHUB_AGENT_TAG: "ghcr.io/ec-release/agent:v1"
      GITHUB_PLUGIN_TAG: "ghcr.io/ec-release/plugins:v1"
      GITHUB_LOADBALANCER_TAG: "ghcr.io/ec-release/lb:v1"
    #- GITHUB_BUILD_TAG="docker.pkg.github.com/ec-release/oci/build:v1"
      GITHUB_REGISTRY: "https://ghcr.io"
      GITHUB_USR: "ayasuda-ge"
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Container Runtime Building
        env:
          EC_REV_V1: v1.hokkaido.213
        run: |
          cd ./spec/agent && docker build -t $DOCKER_HUB_AGENT_TAG --build-arg EC_REV_V1=${EC_REV_V1} . && cd -
          cd ./spec/plugin && docker build -t $DOCKER_HUB_PLUGIN_TAG --build-arg EC_REV_V1=${EC_REV_V1} . && cd -
          cd ./spec/loadbalancer && docker build -t $DOCKER_HUB_LOADBALANCER_TAG --build-arg EC_REV_V1=${EC_REV_V1} . && cd -
   
      - name: Container Test
        env:
          EC_REV_V1: v1.hokkaido.213
        run: |
          echo hello world
      - name: Container Images Deployment
        if: github.event.pull_request.merged == true
        env:
          DOCKER_USERNAME: apoloyasudadocker
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          REGISTRY_TKN_GITHUB: ${{secrets.REGISTRY_TKN_GITHUB}}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push $DOCKER_HUB_AGENT_TAG
          docker push $DOCKER_HUB_PLUGIN_TAG
          docker push $DOCKER_HUB_LOADBALANCER_TAG
          docker tag $DOCKER_HUB_AGENT_TAG $GITHUB_AGENT_TAG
          docker tag $DOCKER_HUB_PLUGIN_TAG $GITHUB_PLUGIN_TAG
          docker tag $DOCKER_HUB_LOADBALANCER_TAG $GITHUB_LOADBALANCER_TAG
          echo $REGISTRY_TKN_GITHUB | docker login $GITHUB_REGISTRY -u $GITHUB_USR --password-stdin
          docker push $GITHUB_AGENT_TAG
          docker push $GITHUB_PLUGIN_TAG
          docker push $GITHUB_LOADBALANCER_TAG 
    
